<# : batch portion
@setlocal DisableDelayedExpansion
@echo off
Color 0F
echo "%*"|find /i "-el" >nul && set _elev=1
set arg="""%~f0""" -el
setlocal EnableDelayedExpansion
>nul 2>&1 fltmc || >nul 2>&1 net session || (
    if not defined _elev (
		powershell -nop -c "saps cmd.exe '/c', '!arg!' -Verb RunAs" >nul 2>&1 && exit /b 0
	)
	echo.
	echo This script require administrator privileges.
	echo To do so, right click on this script and select 'Run as administrator'.
	pause
    exit 1
)
where pwsh.exe >nul 2>&1 && set "ps1=pwsh" || set "ps1=powershell"
%ps1% -nop -ep Bypass -c "Get-Content '%~f0' -Raw | iex"
goto :eof
: end batch / begin powershell #>

$Host.UI.RawUI.WindowTitle = 'Widgets (Administrator)'

	function Get-FileFromWeb {
	param([string]$URL,[string]$File)
	function Show-Progress {
	param([single]$T,[single]$C,[int]$B=10)
	$p=$C/$T;$pc=$p*100
	if($psISE){Write-Progress '' -Id 0 -PercentComplete $pc}
	else{Write-Host -NoNewLine "`r  $(''.PadRight($B*$p,9608).PadRight($B,9617))  $($pc.ToString('##0.00').PadLeft(6)) % "}
	}
	[Net.ServicePointManager]::SecurityProtocol='Tls12,Tls13'
	Add-Type -A System.Net.Http -ea 0; $c=[Net.Http.HttpClient]::new()
	if($File -like '.\*'){$File=Join-Path (pwd) $File.Substring(2)}
	if($File -and !(Split-Path $File)){$File=Join-Path (pwd) $File}
	$d=[IO.Path]::GetDirectoryName($File);if($d -and !(Test-Path $d)){[IO.Directory]::CreateDirectory($d)|out-null}
	try{
	$r=$c.GetAsync($URL,[Net.Http.HttpCompletionOption]::ResponseHeadersRead).GetAwaiter().GetResult()
	$r.EnsureSuccessStatusCode()|out-null
	$s=$r.Content.ReadAsStreamAsync().GetAwaiter().GetResult()
	$len=[long]$r.Content.Headers.ContentLength
	$buf=[byte[]]::new(1mb)
	$fs=[IO.File]::Create($File)
	$t=0
	while(($n=$s.Read($buf,0,$buf.Length)) -gt 0){
	$fs.Write($buf,0,$n);$t+=$n
	if($len -gt 0){Show-Progress $len $t}
	}
	if($len -gt 0){Show-Progress $len $len}
	}finally{
	if($fs){$fs.Close()}
	if($s){$s.Close()}
	$c.Dispose()
	}
	}

Write-Host "1. Telemetry: Off (Recommended)"
Write-Host "2. Telemetry: Default"
while ($true) {
    $choice = Read-Host " "
    if ($choice -match '^[1-2]$') {
    	switch ($choice) {
    		1 {
				
				$ProgressPreference='SilentlyContinue'
				cls; write-host 'Disabling: Telemetry. Please wait . . .'
				# disable defender telemetry
				Set-MpPreference -CloudBlockLevel 0 -Force | Out-Null
				Set-MpPreference -SubmitSamplesConsent 2 -Force | Out-Null
				Set-MpPreference -MAPSReporting 0 -Force | Out-Null
				Set-MpPreference -DisableCoreServiceECSIntegration $true -Force | Out-Null
				# run WindowsSpyBlocker & apply telemetry blocking rules
				$exe="$env:TEMP\WindowsSpyBlocker.exe";Get-FileFromWeb 'https://github.com/crazy-max/WindowsSpyBlocker/releases/latest/download/WindowsSpyBlocker.exe' $exe
				cmd /c "(echo 1 & timeout /t 1 >nul & echo 1 & timeout /t 1 >nul & echo 1 & timeout /t 1 >nul & echo exit) | %tmp%\WindowsSpyBlocker.exe" *>$null			
				# disable firewall
				netsh advfirewall set allprofiles state off | out-null; reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.SecurityAndMaintenance" /v "Enabled" /t REG_DWORD /d 0 /f > $null 2>&1
				# download & start wpd
				$zip="$env:TEMP\WPD.zip";Get-FileFromWeb 'https://wpd.app/get/latest.zip' $zip;Expand-Archive $zip "$env:TEMP" -force; saps -wait "$env:TEMP\wpd.exe" "-nosplash -pro -noappx -includeAdv -defender on -wfp off -privacyAll -close"
				# revert stuff
				# saps -wait "$env:TEMP\wpd.exe" "-nosplash -revert LetAppsAccessMicrophone LetAppsAccessCamera LetAppsAccessNotifications CDPUserSvc wuauserv WaaSMedicSvc UsoSvc bUpdate -close"				
				# create config file
				$config = @'
P001	+	# Disable sharing of handwriting data (Category: Privacy)
P002	+	# Disable sharing of handwriting error reports (Category: Privacy)
P003	+	# Disable Inventory Collector (Category: Privacy)
P004	+	# Disable camera in logon screen (Category: Privacy)
P005	+	# Disable and reset Advertising ID and info for the machine (Category: Privacy)
P006	+	# Disable and reset Advertising ID and info for current user (Category: Privacy)
P008	+	# Disable transmission of typing information (Category: Privacy)
P026	+	# Disable advertisements via Bluetooth (Category: Privacy)
P027	+	# Disable the Windows Customer Experience Improvement Program (Category: Privacy)
P028	+	# Disable backup of text messages into the cloud (Category: Privacy)
P064	+	# Disable suggestions in the timeline (Category: Privacy)
P065	+	# Disable suggestions in Start (Category: Privacy)
P066	+	# Disable tips, tricks, and suggestions when using Windows (Category: Privacy)
P067	+	# Disable showing suggested content in the Settings app (Category: Privacy)
P070	+	# Disable the possibility of suggesting to finish the setup of the device (Category: Privacy)
P069	+	# Disable Windows Error Reporting (Category: Privacy)
P009	+	# Disable biometrical features (Category: Privacy)
P010	-	# Disable app notifications (Category: Privacy)
P015	+	# Disable access to local language for browsers (Category: Privacy)
P068	+	# Disable text suggestions when typing on the software keyboard (Category: Privacy)
P016	+	# Disable sending URLs from apps to Windows Store (Category: Privacy)
A001	+	# Disable recordings of user activity (Category: Activity History and Clipboard)
A002	+	# Disable storing users' activity history on this device (Category: Activity History and Clipboard)
A003	+	# Disable the submission of user activities to Microsoft (Category: Activity History and Clipboard)
A004	+	# Disable storage of clipboard history for whole machine (Category: Activity History and Clipboard)
A006	+	# Disable storage of clipboard history for current user (Category: Activity History and Clipboard)
A005	+	# Disable the transfer of the clipboard to other devices via the cloud (Category: Activity History and Clipboard)
P007	+	# Disable app access to user account information on this device (Category: App Privacy)
P036	+	# Disable app access to user account information for current user (Category: App Privacy)
P025	+	# Disable Windows tracking of app starts (Category: App Privacy)
P033	+	# Disable app access to diagnostics information on this device (Category: App Privacy)
P023	+	# Disable app access to diagnostics information for current user (Category: App Privacy)
P056	-	# Disable app access to device location on this device (Category: App Privacy)
P057	-	# Disable app access to device location for current user (Category: App Privacy)
P012	-	# Disable app access to camera on this device (Category: App Privacy)
P034	-	# Disable app access to camera for current user (Category: App Privacy)
P013	-	# Disable app access to microphone on this device (Category: App Privacy)
P035	-	# Disable app access to microphone for current user (Category: App Privacy)
P062	+	# Disable app access to use voice activation for current user (Category: App Privacy)
P063	+	# Disable app access to use voice activation when device is locked for current user (Category: App Privacy)
P081	+	# Disable the standard app for the headset button (Category: App Privacy)
P047	-	# Disable app access to notifications on this device (Category: App Privacy)
P019	-	# Disable app access to notifications for current user (Category: App Privacy)
P048	+	# Disable app access to motion on this device (Category: App Privacy)
P049	+	# Disable app access to movements for current user (Category: App Privacy)
P020	+	# Disable app access to contacts on this device (Category: App Privacy)
P037	+	# Disable app access to contacts for current user (Category: App Privacy)
P011	+	# Disable app access to calendar on this device (Category: App Privacy)
P038	+	# Disable app access to calendar for current user (Category: App Privacy)
P050	+	# Disable app access to phone calls on this device (Category: App Privacy)
P051	+	# Disable app access to phone calls for current user (Category: App Privacy)
P018	+	# Disable app access to call history on this device (Category: App Privacy)
P039	+	# Disable app access to call history for current user (Category: App Privacy)
P021	+	# Disable app access to email on this device (Category: App Privacy)
P040	+	# Disable app access to email for current user (Category: App Privacy)
P022	+	# Disable app access to tasks on this device (Category: App Privacy)
P041	+	# Disable app access to tasks for current user (Category: App Privacy)
P014	+	# Disable app access to messages on this device (Category: App Privacy)
P042	+	# Disable app access to messages for current user (Category: App Privacy)
P052	+	# Disable app access to radios on this device (Category: App Privacy)
P053	+	# Disable app access to radios for current user (Category: App Privacy)
P054	+	# Disable app access to unpaired devices on this device (Category: App Privacy)
P055	+	# Disable app access to unpaired devices for current user (Category: App Privacy)
P029	+	# Disable app access to documents on this device (Category: App Privacy)
P043	+	# Disable app access to documents for current user (Category: App Privacy)
P030	+	# Disable app access to images on this device (Category: App Privacy)
P044	+	# Disable app access to images for current user (Category: App Privacy)
P031	+	# Disable app access to videos on this device (Category: App Privacy)
P045	+	# Disable app access to videos for current user (Category: App Privacy)
P032	+	# Disable app access to the file system on this device (Category: App Privacy)
P046	+	# Disable app access to the file system for current user (Category: App Privacy)
P058	+	# Disable app access to wireless equipment on this device (Category: App Privacy)
P059	+	# Disable app access to wireless technology for current user (Category: App Privacy)
P060	+	# Disable app access to eye tracking on this device (Category: App Privacy)
P061	+	# Disable app access to eye tracking for current user (Category: App Privacy)
P071	+	# Disable the ability for apps to take screenshots on this device (Category: App Privacy)
P072	+	# Disable the ability for apps to take screenshots for current user (Category: App Privacy)
P073	+	# Disable the ability for desktop apps to take screenshots for current user (Category: App Privacy)
P074	+	# Disable the ability for apps to take screenshots without borders on this device (Category: App Privacy)
P075	+	# Disable the ability for apps to take screenshots without borders for current user (Category: App Privacy)
P076	+	# Disable the ability for desktop apps to take screenshots without margins for current user (Category: App Privacy)
P077	+	# Disable app access to music libraries on this device (Category: App Privacy)
P078	+	# Disable app access to music libraries for current user (Category: App Privacy)
P079	+	# Disable app access to downloads folder on this device (Category: App Privacy)
P080	+	# Disable app access to downloads folder for current user (Category: App Privacy)
P024	+	# Prohibit apps from running in the background (Category: App Privacy)
S001	+	# Disable password reveal button (Category: Security)
S002	+	# Disable user steps recorder (Category: Security)
S003	+	# Disable telemetry (Category: Security)
S008	+	# Disable Internet access of Windows Media Digital Rights Management (DRM) (Category: Security)
E101	+	# Disable tracking in the web (Category: Microsoft Edge (new version based on Chromium))
E201	+	# Disable tracking in the web (Category: Microsoft Edge (new version based on Chromium))
E115	+	# Disable check for saved payment methods by sites (Category: Microsoft Edge (new version based on Chromium))
E215	+	# Disable check for saved payment methods by sites (Category: Microsoft Edge (new version based on Chromium))
E118	+	# Disable personalizing advertising, search, news and other services (Category: Microsoft Edge (new version based on Chromium))
E218	+	# Disable personalizing advertising, search, news and other services (Category: Microsoft Edge (new version based on Chromium))
E107	+	# Disable automatic completion of web addresses in address bar (Category: Microsoft Edge (new version based on Chromium))
E207	+	# Disable automatic completion of web addresses in address bar (Category: Microsoft Edge (new version based on Chromium))
E111	+	# Disable user feedback in toolbar (Category: Microsoft Edge (new version based on Chromium))
E211	+	# Disable user feedback in toolbar (Category: Microsoft Edge (new version based on Chromium))
E112	+	# Disable storing and autocompleting of credit card data on websites (Category: Microsoft Edge (new version based on Chromium))
E212	+	# Disable storing and autocompleting of credit card data on websites (Category: Microsoft Edge (new version based on Chromium))
E109	+	# Disable form suggestions (Category: Microsoft Edge (new version based on Chromium))
E209	+	# Disable form suggestions (Category: Microsoft Edge (new version based on Chromium))
E121	+	# Disable suggestions from local providers (Category: Microsoft Edge (new version based on Chromium))
E221	+	# Disable suggestions from local providers (Category: Microsoft Edge (new version based on Chromium))
E103	+	# Disable search and website suggestions (Category: Microsoft Edge (new version based on Chromium))
E203	+	# Disable search and website suggestions (Category: Microsoft Edge (new version based on Chromium))
E123	+	# Disable shopping assistant in Microsoft Edge (Category: Microsoft Edge (new version based on Chromium))
E223	+	# Disable shopping assistant in Microsoft Edge (Category: Microsoft Edge (new version based on Chromium))
E124	+	# Disable Edge bar (Category: Microsoft Edge (new version based on Chromium))
E224	+	# Disable Edge bar (Category: Microsoft Edge (new version based on Chromium))
E128	+	# Disable Sidebar in Microsoft Edge (Category: Microsoft Edge (new version based on Chromium))
E228	+	# Disable Sidebar in Microsoft Edge (Category: Microsoft Edge (new version based on Chromium))
E129	+	# Disable the Microsoft Account Sign-In Button (Category: Microsoft Edge (new version based on Chromium))
E229	+	# Disable the Microsoft Account Sign-In Button (Category: Microsoft Edge (new version based on Chromium))
E130	+	# Disable Enhanced Spell Checking (Category: Microsoft Edge (new version based on Chromium))
E230	+	# Disable Enhanced Spell Checking (Category: Microsoft Edge (new version based on Chromium))
E119	+	# Disable use of web service to resolve navigation errors (Category: Microsoft Edge (new version based on Chromium))
E219	+	# Disable use of web service to resolve navigation errors (Category: Microsoft Edge (new version based on Chromium))
E120	+	# Disable suggestion of similar sites when website cannot be found (Category: Microsoft Edge (new version based on Chromium))
E220	+	# Disable suggestion of similar sites when website cannot be found (Category: Microsoft Edge (new version based on Chromium))
E122	+	# Disable preload of pages for faster browsing and searching (Category: Microsoft Edge (new version based on Chromium))
E222	+	# Disable preload of pages for faster browsing and searching (Category: Microsoft Edge (new version based on Chromium))
E125	+	# Disable saving passwords for websites (Category: Microsoft Edge (new version based on Chromium))
E225	+	# Disable saving passwords for websites (Category: Microsoft Edge (new version based on Chromium))
E126	+	# Disable site safety services for more information about a visited website (Category: Microsoft Edge (new version based on Chromium))
E226	+	# Disable site safety services for more information about a visited website (Category: Microsoft Edge (new version based on Chromium))
E131	+	# Disable automatic redirection from Internet Explorer to Microsoft Edge (Category: Microsoft Edge (new version based on Chromium))
E106	-	# Disable SmartScreen Filter (Category: Microsoft Edge (new version based on Chromium))
E206	-	# Disable SmartScreen Filter (Category: Microsoft Edge (new version based on Chromium))
E127	+	# Disable typosquatting checker for site addresses (Category: Microsoft Edge (new version based on Chromium))
E227	+	# Disable typosquatting checker for site addresses (Category: Microsoft Edge (new version based on Chromium))
E001	+	# Disable tracking in the web (Category: Microsoft Edge (legacy version))
E002	+	# Disable page prediction (Category: Microsoft Edge (legacy version))
E003	+	# Disable search and website suggestions (Category: Microsoft Edge (legacy version))
E008	+	# Disable Cortana in Microsoft Edge (Category: Microsoft Edge (legacy version))
E007	+	# Disable automatic completion of web addresses in address bar (Category: Microsoft Edge (legacy version))
E010	+	# Disable showing search history (Category: Microsoft Edge (legacy version))
E011	+	# Disable user feedback in toolbar (Category: Microsoft Edge (legacy version))
E012	+	# Disable storing and autocompleting of credit card data on websites (Category: Microsoft Edge (legacy version))
E009	+	# Disable form suggestions (Category: Microsoft Edge (legacy version))
E004	+	# Disable sites saving protected media licenses on my device (Category: Microsoft Edge (legacy version))
E005	+	# Do not optimize web search results on the task bar for screen reader (Category: Microsoft Edge (legacy version))
E013	+	# Disable Microsoft Edge launch in the background (Category: Microsoft Edge (legacy version))
E014	+	# Disable loading the start and new tab pages in the background (Category: Microsoft Edge (legacy version))
E006	-	# Disable SmartScreen Filter (Category: Microsoft Edge (legacy version))
Y001	+	# Disable synchronization of all settings (Category: Synchronization of Windows Settings)
Y002	+	# Disable synchronization of design settings (Category: Synchronization of Windows Settings)
Y003	+	# Disable synchronization of browser settings (Category: Synchronization of Windows Settings)
Y004	+	# Disable synchronization of credentials (passwords) (Category: Synchronization of Windows Settings)
Y005	+	# Disable synchronization of language settings (Category: Synchronization of Windows Settings)
Y006	+	# Disable synchronization of accessibility settings (Category: Synchronization of Windows Settings)
Y007	+	# Disable synchronization of advanced Windows settings (Category: Synchronization of Windows Settings)
C012	+	# Disable and reset Cortana (Category: Cortana (Personal Assistant))
C002	+	# Disable Input Personalization (Category: Cortana (Personal Assistant))
C013	+	# Disable online speech recognition (Category: Cortana (Personal Assistant))
C007	+	# Cortana and search are disallowed to use location (Category: Cortana (Personal Assistant))
C008	+	# Disable web search from Windows Desktop Search (Category: Cortana (Personal Assistant))
C009	+	# Disable display web results in Search (Category: Cortana (Personal Assistant))
C010	+	# Disable download and updates of speech recognition and speech synthesis models (Category: Cortana (Personal Assistant))
C011	+	# Disable cloud search (Category: Cortana (Personal Assistant))
C014	+	# Disable Cortana above lock screen (Category: Cortana (Personal Assistant))
C015	+	# Disable the search highlights in the taskbar (Category: Cortana (Personal Assistant))
C101	+	# Disable the Windows Copilot (Category: Windows AI)
C201	+	# Disable the Windows Copilot (Category: Windows AI)
C204	+	# Disable the provision of recall functionality to all users (Category: Windows AI)
C205	+	# Disable the Image Creator in Microsoft Paint (Category: Windows AI)
C102	+	# Disable the Copilot button from the taskbar (Category: Windows AI)
C103	+	# Disable Windows Copilot+ Recall (Category: Windows AI)
C203	+	# Disable Windows Copilot+ Recall (Category: Windows AI)
C206	+	# Disable Cocreator in Microsoft Paint (Category: Windows AI)
C207	+	# Disable AI-powered image fill in Microsoft Paint (Category: Windows AI)
L001	-	# Disable functionality to locate the system (Category: Location Services)
L003	+	# Disable scripting functionality to locate the system (Category: Location Services)
L004	+	# Disable sensors for locating the system and its orientation (Category: Location Services)
L005	-	# Disable Windows Geolocation Service (Category: Location Services)
U001	+	# Disable application telemetry (Category: User Behavior)
U004	+	# Disable diagnostic data from customizing user experiences for whole machine (Category: User Behavior)
U005	+	# Disable the use of diagnostic data for a tailor-made user experience for current user (Category: User Behavior)
U006	+	# Disable diagnostic log collection (Category: User Behavior)
U007	+	# Disable downloading of OneSettings configuration settings (Category: User Behavior)
W001	+	# Disable Windows Update via peer-to-peer (Category: Windows Update)
W011	+	# Disable updates to the speech recognition and speech synthesis modules. (Category: Windows Update)
W004	+	# Activate deferring of upgrades (Category: Windows Update)
W005	+	# Disable automatic downloading manufacturers' apps and icons for devices (Category: Windows Update)
W010	+	# Disable automatic driver updates through Windows Update (Category: Windows Update)
W009	+	# Disable automatic app updates through Windows Update (Category: Windows Update)
P017	+	# Disable Windows dynamic configuration and update rollouts (Category: Windows Update)
W006	+	# Disable automatic Windows Updates (Category: Windows Update)
W008	+	# Disable Windows Updates for other products (e.g. Microsoft Office) (Category: Windows Update)
M006	+	# Disable occassionally showing app suggestions in Start menu (Category: Windows Explorer)
M011	+	# Do not show recently opened items in Jump Lists on "Start" or the taskbar (Category: Windows Explorer)
M010	+	# Disable ads in Windows Explorer/OneDrive (Category: Windows Explorer)
O003	-	# Disable OneDrive access to network before login (Category: Windows Explorer)
O001	-	# Disable Microsoft OneDrive (Category: Windows Explorer)
S012	-	# Disable Microsoft SpyNet membership (Category: Microsoft Defender and Microsoft SpyNet)
S013	-	# Disable submitting data samples to Microsoft (Category: Microsoft Defender and Microsoft SpyNet)
S014	-	# Disable reporting of malware infection information (Category: Microsoft Defender and Microsoft SpyNet)
K001	+	# Disable Windows Spotlight (Category: Lock Screen)
K002	+	# Disable fun facts, tips, tricks, and more on your lock screen (Category: Lock Screen)
K005	+	# Disable notifications on lock screen (Category: Lock Screen)
D001	+	# Disable access to mobile devices (Category: Mobile Devices)
D002	-	# Disable Phone Link app (Category: Mobile Devices)
D003	+	# Disable showing suggestions for using mobile devices with Windows (Category: Mobile Devices)
D104	+	# Disable connecting the PC to mobile devices (Category: Mobile Devices)
M025	+	# Disable search with AI in search box (Category: Search)
M003	+	# Disable extension of Windows search with Bing (Category: Search)
M015	+	# Disable People icon in the taskbar (Category: Taskbar)
M016	+	# Disable search box in task bar (Category: Taskbar)
M017	+	# Disable "Meet now" in the task bar on this device (Category: Taskbar)
M018	+	# Disable "Meet now" in the task bar for current user (Category: Taskbar)
M019	-	# Disable news and interests in the task bar on this device (Category: Taskbar)
M021	-	# Disable widgets in Windows Explorer (Category: Taskbar)
M022	+	# Disable feedback reminders on this device (Category: Miscellaneous)
M001	+	# Disable feedback reminders for current user (Category: Miscellaneous)
M004	+	# Disable automatic installation of recommended Windows Store Apps (Category: Miscellaneous)
M005	+	# Disable tips, tricks, and suggestions while using Windows (Category: Miscellaneous)
M024	+	# Disable Windows Media Player Diagnostics (Category: Miscellaneous)
M012	+	# Disable Key Management Service Online Activation (Category: Miscellaneous)
M013	+	# Disable automatic download and update of map data (Category: Miscellaneous)
M014	+	# Disable unsolicited network traffic on the offline maps settings page (Category: Miscellaneous)
M026	+	# Disable remote assistance connections to this computer (Category: Miscellaneous)
M027	+	# Disable remote connections to this computer (Category: Miscellaneous)
M028	+	# Disable the desktop icon for information on "Windows Spotlight" (Category: Miscellaneous)
N001	+	# Disable Network Connectivity Status Indicator (Category: Miscellaneous)
'@
				Set-Content -Path "$env:TEMP\ooshutup10.cfg" -Value $config -Force
				# donwload & start shutup10
				$exe="$env:TEMP\OOSU10.exe"; Get-FileFromWeb 'https://dl5.oo-software.com/files/ooshutup10/OOSU10.exe' $exe;saps $exe "$env:TEMP\ooshutup10.cfg", '/quiet'											
				# disable Intel MM (vPro LMS)
				$svc="LMS";spsv -Name $svc -Force -ea 0;Set-Service -Name $svc -StartupType Disabled -ea 0;sc.exe delete $svc | Out-Null
				gci "$env:windir\System32\DriverStore\FileRepository" -Recurse -Filter "lms.inf*" -ea 0 |% {pnputil /delete-driver $_.Name /uninstall /force | Out-Null}
				"C:\Program Files","${env:ProgramFiles(x86)}" |% {gci $_ -Recurse -Filter LMS.exe -ea 0} | % {takeown /f $_.FullName /a /r /d y | Out-Null;icacls $_.FullName /grant Administrators:F /t /c /q | Out-Null;ri $_.FullName -Force -ea 0}
				# revert important stuff
				$c='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore'; 'microphone','webcam','notifications' | % { sp "$c\$_" Value Allow -ea 0 }
				'wuauserv','UsoSvc','WaaSMedicSvc','CDPUserSvc' | % { Set-Service $_ -StartupType Manual -ea 0; Start-Service $_ -ea 0 *>$null }
				cls;write-host "Restart to apply . . .";$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown");exit
				
	      	}
    		2 {
				
				$ProgressPreference = 'SilentlyContinue'
				# WindowsSpyBlocker
				$exe="$env:TEMP\WindowsSpyBlocker.exe";Get-FileFromWeb 'https://github.com/crazy-max/WindowsSpyBlocker/releases/latest/download/WindowsSpyBlocker.exe' $exe
				cmd /c "(echo 1 & timeout /t 1 >nul & echo 1 & timeout /t 1 >nul & echo 4 & timeout /t 1 >nul & echo exit) | %tmp%\WindowsSpyBlocker.exe"
				# WPD
				netsh advfirewall set allprofiles state on | Out-Null
				reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.SecurityAndMaintenance" /v "Enabled" /t REG_DWORD /d 1 /f > $null 2>&1
				$zip="$env:TEMP\WPD.zip";Get-FileFromWeb 'https://wpd.app/get/latest.zip' $zip;Expand-Archive $zip "$env:TEMP" -force; saps -wait "$env:TEMP\wpd.exe" "-wfp on -default -close"
				# create config file
				$config = @'
P001	-	# Condivisione dei dati scritti a mano disattivato (Categoria: Privacy)
P002	-	# Condivisione dei rapporti d'errore di scrittura a mano disattivata (Categoria: Privacy)
P003	-	# Inventory Collector disattivata (Categoria: Privacy)
P004	-	# Fotocamera in schermata login disattivata (Categoria: Privacy)
P005	-	# Disattivare e reimpostare l'ID pubblicità per l'intero computer (Categoria: Privacy)
P006	-	# Disabilitare e reimpostare l'ID annuncio per l'utente corrente (Categoria: Privacy)
P008	-	# Trasmissione di dati sulla digitazione disattivata (Categoria: Privacy)
P026	-	# Disattivare le publicità tramite Bluetooth (Categoria: Privacy)
P027	-	# Disattiva il Customer Experience Improvement Program di Windows (Categoria: Privacy)
P028	-	# Disattiva il backup dei messaggi di SMS nel cloud (Categoria: Privacy)
P064	-	# Disabilitare i suggerimenti nella sequenza temporale (Categoria: Privacy)
P065	-	# Disabilitare i suggerimenti in Start (Categoria: Privacy)
P066	-	# Disattivare suggerimenti, trucchi e suggerimenti quando si usa Windows (Categoria: Privacy)
P067	-	# Disabilitare la visualizzazione dei contenuti suggeriti nell'app Impostazioni (Categoria: Privacy)
P070	-	# Disabilitare la possibilità di suggerire di completare la configurazione del dispositivo (Categoria: Privacy)
P069	-	# Disattiva Segnalazione errori Windows (Categoria: Privacy)
P009	-	# Caratteristiche biometriche disattivata (Categoria: Privacy)
P010	-	# App notifiche disattivato (Categoria: Privacy)
P015	-	# L'accesso alla lingua locale per i browser disattivato (Categoria: Privacy)
P068	-	# Disabilitare i suggerimenti di testo quando si digita sulla tastiera del software (Categoria: Privacy)
P016	-	# L'invio dei URL tramite delle app al Windows Store disattivato (Categoria: Privacy)
A001	-	# Disabilitare le registrazioni delle attività dell'utente (Categoria: Cronologia attività e Appunti)
A002	-	# Archiviazione dIsable della cronologia delle attività degli utenti in questo dispositivoDIsable storing users' activity history on this device (Categoria: Cronologia attività e Appunti)
A003	-	# Disabilitare l'invio delle attività degli utenti a Microsoft (Categoria: Cronologia attività e Appunti)
A004	-	# Disabilitare l'archiviazione della cronologia degli Appunti per interi computer (Categoria: Cronologia attività e Appunti)
A006	-	# Disabilitare l'archiviazione della cronologia degli Appunti per gli utenti correnti (Categoria: Cronologia attività e Appunti)
A005	-	# Disabilitare il trasferimento degli Appunti ad altri dispositivi tramite il cloud (Categoria: Cronologia attività e Appunti)
P007	-	# Disabilitare l'accesso dell'app alle informazioni sull'account utente in questo dispositivoDisable app access to user account information on this device (Categoria: App Privacy)
P036	-	# Disabilitare l'accesso dell'app alle informazioni sull'account utente per l'utente corrente (Categoria: App Privacy)
P025	-	# Disattivare il Windows tracking dei avviamenti delle app (Categoria: App Privacy)
P033	-	# Disabilitare l'accesso dell'app alle informazioni di diagnostica per il dispositivo (Categoria: App Privacy)
P023	-	# Disabilitare l'accesso dell'app alle informazioni di diagnostica per l'utente corrente (Categoria: App Privacy)
P056	-	# Disabilitare l'accesso dell'app alla posizione del dispositivo in questo dispositivoDisable app access to device location on this device (Categoria: App Privacy)
P057	-	# Disabilitare l'accesso dell'app alla posizione del dispositivo per l'utente corrente (Categoria: App Privacy)
P012	-	# Disabilitare l'accesso dell'app alla fotocamera su questo dispositivo (Categoria: App Privacy)
P034	-	# App accesso alla fotocamera disattivata (Categoria: App Privacy)
P013	-	# Disabilitare l'accesso dell'app al microfono su questo dispositivo (Categoria: App Privacy)
P035	-	# App accesso al microfono disattivata (Categoria: App Privacy)
P062	-	# Disabilitare l'accesso alle app per usare l'attivazione vocale per l'utente corrente (Categoria: App Privacy)
P063	-	# Disabilitare l'accesso all'app per usare l'attivazione vocale quando il dispositivo è bloccato per l'utente corrente (Categoria: App Privacy)
P081	-	# Disabilita l'app predefinita per la pressione del pulsante dell'auricolare (Categoria: App Privacy)
P047	-	# Disabilitare l'accesso dell'app alle notifiche su questo dispositivo (Categoria: App Privacy)
P019	-	# Disattivare l'accesso delle app alle notifiche (Categoria: App Privacy)
P048	-	# Disabilitare l'accesso dell'app al movimento in questo dispositivo (Categoria: App Privacy)
P049	-	# Disabilitare l'accesso dell'app ai movimenti per l'utente corrente (Categoria: App Privacy)
P020	-	# Disabilitare l'accesso alle app ai contatti su questo dispositivo (Categoria: App Privacy)
P037	-	# Disabilitare l'accesso dell'app ai contatti per l'utente corrente (Categoria: App Privacy)
P011	-	# Disabilitare l'accesso dell'app al calendario in questo dispositivo (Categoria: App Privacy)
P038	-	# Disabilitare l'accesso dell'app al calendario per l'utente corrente (Categoria: App Privacy)
P050	-	# Disabilitare l'accesso dell'app alle chiamate telefoniche su questo dispositivo (Categoria: App Privacy)
P051	-	# Disabilitare l'accesso dell'app alle chiamate telefoniche per l'utente corrente (Categoria: App Privacy)
P018	-	# Disabilitare l'accesso dell'app alla cronologia delle chiamate su questo dispositivo (Categoria: App Privacy)
P039	-	# Disabilitare l'accesso dell'app alla cronologia delle chiamate per l'utente corrente (Categoria: App Privacy)
P021	-	# Disabilitare l'accesso dell'app alla posta elettronica in questo dispositivoDisable app access to email on this device (Categoria: App Privacy)
P040	-	# Disattivare l'accesso delle app alla posta elettronica (Categoria: App Privacy)
P022	-	# Disabilitare l'accesso dell'app alle attività in questo dispositivo (Categoria: App Privacy)
P041	-	# Disabilitare l'accesso delle app alle attività per l'utente corrente (Categoria: App Privacy)
P014	-	# Disabilitare l'accesso dell'app ai messaggi in questo dispositivoDisable app access to messages on this device (Categoria: App Privacy)
P042	-	# Disabilitare l'accesso dell'app ai messaggi per l'utente corrente (Categoria: App Privacy)
P052	-	# Disabilitare l'accesso alle app alle radio su questo dispositivo (Categoria: App Privacy)
P053	-	# Disabilitare l'accesso delle app alle radio per l'utente corrente (Categoria: App Privacy)
P054	-	# Disabilita l'accesso all'app ai dispositivi non abbinati su questo dispositivo (Categoria: App Privacy)
P055	-	# Disabilita l'accesso all'app ai dispositivi non associati per l'utente corrente (Categoria: App Privacy)
P029	-	# Disabilitare l'accesso alle app ai documenti in questo dispositivo (Categoria: App Privacy)
P043	-	# Disabilitare l'accesso dell'app ai documenti per l'utente corrente (Categoria: App Privacy)
P030	-	# Disabilitare l'accesso alle app alle immagini in questo dispositivo (Categoria: App Privacy)
P044	-	# Disabilitare l'accesso dell'app alle immagini per l'utente corrente (Categoria: App Privacy)
P031	-	# Disabilitare l'accesso alle app ai video su questo dispositivo (Categoria: App Privacy)
P045	-	# Disabilitare l'accesso alle app ai video per l'utente corrente (Categoria: App Privacy)
P032	-	# Disabilitare l'accesso dell'app al file system su questo dispositivo (Categoria: App Privacy)
P046	-	# Disabilitare l'accesso dell'app al file system per l'utente corrente (Categoria: App Privacy)
P058	-	# Disabilita l'accesso tramite app alle apparecchiature wireless su questo dispositivo (Categoria: App Privacy)
P059	-	# Disabilita l'accesso dell'app alla tecnologia wireless per l'utente corrente (Categoria: App Privacy)
P060	-	# Disabilitare l'accesso alle app per il monitoraggio otculare su questo dispositivo (Categoria: App Privacy)
P061	-	# Disabilitare l'accesso dell'app al monitoraggio oculare per l'utente corrente (Categoria: App Privacy)
P024	-	# Bloccare l'esecuzione delle app in background (Categoria: App Privacy)
S001	-	# Pulsante Rivela password disattivato (Categoria: Sicurezza)
S002	-	# Registrazione azioni utente disattivata (Categoria: Sicurezza)
S003	-	# Telemetria disattivata (Categoria: Sicurezza)
S008	-	# L'accesso a Internet di Windows Media Digital Rights Management ( DRM ) disattivata (Categoria: Sicurezza)
E101	-	# Disattiva il tracciamento sul web (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E201	-	# Disattiva il tracciamento sul web (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E115	-	# Disabilitare il controllo dei metodi di pagamento salvati per i siti (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E215	-	# Disabilitare il controllo dei metodi di pagamento salvati per i siti (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E118	-	# Disabilitare la personalizzazione di pubblicità, ricerca, notizie e altri servizi (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E218	-	# Disabilitare la personalizzazione di pubblicità, ricerca, notizie e altri servizi (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E107	-	# Disattivare il completamento automatico degli indirizzi web nella barra degli indirizzi (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E207	-	# Disattivare il completamento automatico degli indirizzi web nella barra degli indirizzi (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E111	-	# Disabilita il feedback degli utenti nella barra degli strumenti (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E211	-	# Disabilita il feedback degli utenti nella barra degli strumenti (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E112	-	# Disattivare l'archiviazione automatica e il riempimento dei dati della carta di credito (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E212	-	# Disattivare l'archiviazione automatica e il riempimento dei dati della carta di credito (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E109	-	# Disattiva il completamento automatico (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E209	-	# Disattiva il completamento automatico (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E121	-	# Disabilitare i suggerimenti dei provider locali (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E221	-	# Disabilitare i suggerimenti dei provider locali (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E103	-	# Disattiva suggerimenti per la ricerca e I siti web (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E203	-	# Disattiva suggerimenti per la ricerca e I siti web (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E123	-	# Disabilitare l'Assistente acquisti in Microsoft Edge (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E223	-	# Disabilitare l'Assistente acquisti in Microsoft Edge (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E124	-	# Disabilitare la barra dei bordi (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E224	-	# Disabilitare la barra dei bordi (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E128	-	# Disattivare la barra laterale in Microsoft Edge (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E228	-	# Disattivare la barra laterale in Microsoft Edge (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E129	-	# Disabilita il pulsante di accesso all'account Microsoft (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E229	-	# Disabilita il pulsante di accesso all'account Microsoft (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E130	-	# Disabilita il controllo ortografico avanzato (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E230	-	# Disabilita il controllo ortografico avanzato (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E119	-	# Disabilitare l'utilizzo del servizio Web per risolvere gli errori di navigazione (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E219	-	# Disabilitare l'utilizzo del servizio Web per risolvere gli errori di navigazione (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E120	-	# Disattiva il suggerimento di siti simili quando non è possibile trovare un sito Web (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E220	-	# Disattiva il suggerimento di siti simili quando non è possibile trovare un sito Web (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E122	-	# Disabilitare il precaricamento delle pagine per una navigazione e una ricerca più veloci (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E222	-	# Disabilitare il precaricamento delle pagine per una navigazione e una ricerca più veloci (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E125	-	# Disabilitare il salvataggio delle password per i siti Web (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E225	-	# Disabilitare il salvataggio delle password per i siti Web (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E126	-	# Disattivare i servizi di sicurezza del sito per ulteriori informazioni su un sito Web visitato (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E226	-	# Disattivare i servizi di sicurezza del sito per ulteriori informazioni su un sito Web visitato (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E131	-	# Disabilita il reindirizzamento automatico da Internet Explorer a Microsoft Edge (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E106	-	# Disattiva filtro SmartScreen (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E206	-	# Disattiva filtro SmartScreen (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E127	-	# Disabilitare il controllo errori di battitura per gli indirizzi dei siti (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E227	-	# Disabilitare il controllo errori di battitura per gli indirizzi dei siti (Categoria: Microsoft Edge (nuova versione basata su Chromium))
E001	-	# Disattiva il tracciamento sul web (Categoria: Microsoft Edge (versione legacy))
E002	-	# Disattiva pagina previsione (Categoria: Microsoft Edge (versione legacy))
E003	-	# Disattiva suggerimenti per la ricerca e I siti web (Categoria: Microsoft Edge (versione legacy))
E008	-	# Disattiva Cortana in Microsoft Edge (Categoria: Microsoft Edge (versione legacy))
E007	-	# Disattivare il completamento automatico degli indirizzi web nella barra degli indirizzi (Categoria: Microsoft Edge (versione legacy))
E010	-	# Disattiva la visualizzazione della cronologia delle ricerche (Categoria: Microsoft Edge (versione legacy))
E011	+	# Disabilita il feedback degli utenti nella barra degli strumenti (Categoria: Microsoft Edge (versione legacy))
E012	-	# Disattivare l'archiviazione automatica e il riempimento dei dati della carta di credito (Categoria: Microsoft Edge (versione legacy))
E009	-	# Disattiva il completamento automatico (Categoria: Microsoft Edge (versione legacy))
E004	-	# Disattiva il salvataggio delle licenze multimediali protetti sul mio dispositivo (Categoria: Microsoft Edge (versione legacy))
E005	-	# Non ottimizzare i risultati di ricerca web sulla barra delle applicazioni per lettore di schermo (Categoria: Microsoft Edge (versione legacy))
E013	-	# Disattivare Microsoft Edge in background (Categoria: Microsoft Edge (versione legacy))
E014	-	# Disattivare il caricamento delle schede iniziale e nuova in background (Categoria: Microsoft Edge (versione legacy))
E006	-	# Disattiva filtro SmartScreen (Categoria: Microsoft Edge (versione legacy))
F002	-	# Disabilitare la telemetria per Microsoft Office (Categoria: Ufficio Microsoft)
F014	-	# Disabilitare l'invio dei dati di diagnostica (Categoria: Ufficio Microsoft)
F015	-	# Disabilitare la partecipazione al programma Analisi utilizzo software (Categoria: Ufficio Microsoft)
F016	-	# Disattivare la visualizzazione delle informazioni di LinkedIn (Categoria: Ufficio Microsoft)
F001	-	# Disabilitare la previsione del testo in linea nelle e-mail (Categoria: Ufficio Microsoft)
F003	-	# Disabilitare la registrazione per l'agente di telemetria di Microsoft Office (Categoria: Ufficio Microsoft)
F004	-	# Disabilitare il caricamento dei dati per l'agente di telemetria di Microsoft Office (Categoria: Ufficio Microsoft)
F005	-	# Offuscare i nomi dei file durante il caricamento dei dati di telemetria (Categoria: Ufficio Microsoft)
F007	-	# Disattivare i sondaggi di Microsoft Office (Categoria: Ufficio Microsoft)
F008	-	# Disabilitare il feedback a Microsoft (Categoria: Ufficio Microsoft)
F009	-	# Disattivare il monitoraggio dei feedback di Microsoft (Categoria: Ufficio Microsoft)
F017	-	# Disattivare il monitoraggio dei feedback di Microsoft (Categoria: Ufficio Microsoft)
F006	-	# Disattivare la ricezione automatica degli aggiornamenti (Categoria: Ufficio Microsoft)
F010	-	# Disattivare le esperienze connesse in Office (Categoria: Ufficio Microsoft)
F011	-	# Disattivare le esperienze connesse con l'analisi dei contenuti (Categoria: Ufficio Microsoft)
F012	-	# Disabilitare il download di contenuti online per le esperienze connesse (Categoria: Ufficio Microsoft)
F013	-	# Disabilitare le esperienze connesse facoltative in Office (Categoria: Ufficio Microsoft)
Y001	-	# Disattiva la sincronizzazione di tutte le impostazioni (Categoria: Sincronizzazione di Impostazioni di Windows)
Y002	-	# Disattiva la sincronizzazione delle impostazioni di progetto (Categoria: Sincronizzazione di Impostazioni di Windows)
Y003	-	# Disattivare la sincronizzazione delle impostazioni del browser (Categoria: Sincronizzazione di Impostazioni di Windows)
Y004	-	# Disattiva la sincronizzazione delle credenziali ( password ) (Categoria: Sincronizzazione di Impostazioni di Windows)
Y005	-	# Disattiva la sincronizzazione delle impostazioni di lingua (Categoria: Sincronizzazione di Impostazioni di Windows)
Y006	-	# Disattiva la sincronizzazione delle impostazioni di accessibilità (Categoria: Sincronizzazione di Impostazioni di Windows)
Y007	-	# Disattiva la sincronizzazione delle impostazioni avanzate di Windows (Categoria: Sincronizzazione di Impostazioni di Windows)
C012	-	# Cortana reset e disattivata (Categoria: Cortana (Assistente personale))
C002	-	# Input personalizzata disattivato (Categoria: Cortana (Assistente personale))
C013	-	# Disabilitare il riconoscimento vocale online (Categoria: Cortana (Assistente personale))
C007	-	# Cortana e Ricerca non sono autorizzati a utilizzare la posizione (Categoria: Cortana (Assistente personale))
C008	-	# Ricerca web dal Windows Desktop Search disattivata (Categoria: Cortana (Assistente personale))
C009	-	# La visualizzazione dei risultati web in Ricerca disattivata (Categoria: Cortana (Assistente personale))
C010	-	# Disattivare i download e aggiornamenti dei modeli di riconoscimento e di sintesi vocale (Categoria: Cortana (Assistente personale))
C011	-	# Disattiva la ricerca cloud (Categoria: Cortana (Assistente personale))
C014	-	# Disabilita Cortana sopra la schermata di blocco (Categoria: Cortana (Assistente personale))
C015	-	# Disattivazione delle evidenziazioni di ricerca nella barra delle applicazioni (Categoria: Cortana (Assistente personale))
C101	-	# Disattivazione del copilota di Windows (Categoria: Windows AI)
C103	-	# Disabilita il richiamo di Windows Copilot+ (Categoria: Windows AI)
C203	-	# Disabilita il richiamo di Windows Copilot+ (Categoria: Windows AI)
L001	-	# Funzionalità per individuare il sistema (Categoria: Servizi individuare)
L003	-	# Funzionalità di scripting per individuare il sistema disattivata (Categoria: Servizi individuare)
L004	-	# Sensori per individuare il sistema e il suo orientamento (Categoria: Servizi individuare)
L005	-	# Windows Geolocation Service disattivata (Categoria: Servizi individuare)
U001	-	# App di telemetria disattivata (Categoria: Comportamento dell'utente)
U004	-	# Disattivare che I dati di diagnostica personalizza l'esperienza degli utenti (Categoria: Comportamento dell'utente)
U005	-	# Disabilitare l'uso dei dati di diagnostica per un'esperienza utente personalizzata per gli utenti correnti (Categoria: Comportamento dell'utente)
U006	-	# Disabilitare la raccolta dei log di diagnostica (Categoria: Comportamento dell'utente)
U007	-	# Disabilitare il download delle impostazioni di configurazione di OneSettings (Categoria: Comportamento dell'utente)
W001	-	# Windows Update tramite peer-to-peer disattivata (Categoria: Windows Update)
W011	-	# Disattiva gli aggiornamenti ai moduli di riconoscimento vocale e sintesi vocale. (Categoria: Windows Update)
W004	-	# Attiva differimento degli aggiornamenti (Categoria: Windows Update)
W005	-	# Disattiva il download automatico delle applicazioni e le icone dei produttori per i dispositivi (Categoria: Windows Update)
W010	-	# Aggiornamenti automatici dei driver tramite Windows Update disattivata (Categoria: Windows Update)
W009	-	# Aggiornamenti automatici per le app tramite Windows Update disattivata (Categoria: Windows Update)
P017	-	# Disabilitare la configurazione dinamica di Windows e le implementazioni degli aggiornamenti (Categoria: Windows Update)
W006	-	# Aggiornamenti automatici di Windows Updates disattivata (Categoria: Windows Update)
W008	-	# Disattivata Windows Update per altri prodotti ( ad esempio, Microsoft Office ) (Categoria: Windows Update)
M006	-	# Disattivare la visualizzazione saltuaria dei suggerimenti per le app in menu Start (Categoria: Windows Explorer)
M011	-	# Non visualizzare gli elementi aperti di recente in Elenchi di salti su "Start" o sulla barra delle applicazioni (Categoria: Windows Explorer)
M010	-	# Disattiva publicità in Windows Explorer/OneDrive (Categoria: Windows Explorer)
O003	-	# Disattiva l'accesso OneDrive alla rete prima del login (Categoria: Windows Explorer)
O001	-	# Microsoft OneDrive disattivato (Categoria: Windows Explorer)
S012	-	# Appartenenza a Microsoft SpyNet disattivata (Categoria: Microsoft Defender e Microsoft SpyNet)
S013	-	# L’invio dei campioni di dati a Microsoft disattivato (Categoria: Microsoft Defender e Microsoft SpyNet)
S014	-	# Notifica infezione da malware disattivata (Categoria: Microsoft Defender e Microsoft SpyNet)
K001	-	# Disattivare Windows Spotlight (Categoria: Schermata di blocco)
K002	-	# Disattiva divertimento, suggerimenti, trucchi e ancora di più sulla schermata di blocco (Categoria: Schermata di blocco)
K005	-	# Disattiva le notifiche sulla schermata di blocco (Categoria: Schermata di blocco)
D104	-	# Disattivare la connessione del PC ai dispositivi mobili (Categoria: Dispositivi mobili)
M003	-	# Estensione di Windows ricerca con Bing disattivata (Categoria: Ricerca)
M015	-	# Disattiva l'icona Persone nella barra delle applicazioni (Categoria: Barra delle applicazioni)
M016	-	# Disabilita la casella di ricerca nella barra delle applicazioni (Categoria: Barra delle applicazioni)
M017	-	# Disabilitare "Meet now" nella barra delle applicazioni di questo dispositivo (Categoria: Barra delle applicazioni)
M018	-	# Disabilitare "Meet now" nella barra delle applicazioni per l'utente corrente (Categoria: Barra delle applicazioni)
M019	-	# Disabilitare notizie e interessi nella barra delle applicazioni (Categoria: Barra delle applicazioni)
M022	-	# Disabilita i promemoria di feedback su questo dispositivo (Categoria: Miscellanea)
M001	-	# Disabilitare i promemoria di feedback per l'utente corrente (Categoria: Miscellanea)
M004	-	# Disattivare l'installazione automatica delle app raccomandati dal Windows Store (Categoria: Miscellanea)
M005	-	# Disattivare i trucchi e suggerimenti durante l'uso di Windows (Categoria: Miscellanea)
M024	-	# Disattivare la diagnostica di Windows Media Player (Categoria: Miscellanea)
M012	-	# Disattiva il servizio di attivazione della gestione delle chiavi online (Categoria: Miscellanea)
M013	-	# Disattiva il download automatico (Categoria: Miscellanea)
M014	-	# Disattiva il traffico di rete non richiesto sulle pagina di mappe offline (Categoria: Miscellanea)
M023	-	# Disabilitare l'installazione di PC Health Check (Categoria: Miscellanea)
M026	-	# Disabilita le connessioni di assistenza remota a questo computer (Categoria: Miscellanea)
M027	-	# Disabilita le connessioni remote a questo computer (Categoria: Miscellanea)
N001	-	# Network Connectivity Status Indicator disattivata (Categoria: Miscellanea)
'@
				Set-Content -Path "$env:TEMP\ooshutup10.cfg" -Value $config -Force
				# donwload & start shutup10
				$exe="$env:TEMP\OOSU10.exe"; Get-FileFromWeb 'https://dl5.oo-software.com/files/ooshutup10/OOSU10.exe' $exe;saps $exe "$env:TEMP\ooshutup10.cfg", '/quiet'
				cls;write-host "Restart to apply . . .";$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown");exit
				
      		}
   		 }
	} else { Write-Host "Invalid input. Please select a valid option (1-2)." }
}
			